<?php
if (!defined('ABSPATH')) exit;

add_filter( 'tribe_countries', function( $countries ) {

    return [

        // ===== EUROPA =====
        'AL' => 'Albânia',
        'DE' => 'Alemanha',
        'AD' => 'Andorra',
        'AT' => 'Áustria',
        'BE' => 'Bélgica',
        'BA' => 'Bósnia e Herzegovina',
        'BG' => 'Bulgária',
        'CY' => 'Chipre',
        'HR' => 'Croácia',
        'DK' => 'Dinamarca',
        'SK' => 'Eslováquia',
        'SI' => 'Eslovénia',
        'ES' => 'Espanha',
        'EE' => 'Estónia',
        'FI' => 'Finlândia',
        'FR' => 'França',
        'GR' => 'Grécia',
        'NL' => 'Países Baixos',
        'HU' => 'Hungria',
        'IE' => 'Irlanda',
        'IS' => 'Islândia',
        'IT' => 'Itália',
        'LV' => 'Letónia',
        'LI' => 'Liechtenstein',
        'LT' => 'Lituânia',
        'LU' => 'Luxemburgo',
        'MT' => 'Malta',
        'MD' => 'Moldávia',
        'MC' => 'Mónaco',
        'ME' => 'Montenegro',
        'MK' => 'Macedónia do Norte',
        'NO' => 'Noruega',
        'PL' => 'Polónia',
        'PT' => 'Portugal',
        'GB' => 'Reino Unido',
        'CZ' => 'República Checa',
        'RO' => 'Roménia',
        'SM' => 'São Marino',
        'RS' => 'Sérvia',
        'SE' => 'Suécia',
        'CH' => 'Suíça',
        'UA' => 'Ucrânia',

        // ===== AMÉRICA =====
        'AR' => 'Argentina',
        'BO' => 'Bolívia',
        'BR' => 'Brasil',
        'CA' => 'Canadá',
        'CL' => 'Chile',
        'CO' => 'Colômbia',
        'CR' => 'Costa Rica',
        'CU' => 'Cuba',
        'DO' => 'República Dominicana',
        'EC' => 'Equador',
        'SV' => 'El Salvador',
        'GT' => 'Guatemala',
        'HN' => 'Honduras',
        'MX' => 'México',
        'NI' => 'Nicarágua',
        'PA' => 'Panamá',
        'PY' => 'Paraguai',
        'PE' => 'Peru',
        'US' => 'Estados Unidos',
        'UY' => 'Uruguai',
        'VE' => 'Venezuela',

        // ===== ÁFRICA =====
        'AO' => 'Angola',
        'DZ' => 'Argélia',
        'CM' => 'Camarões',
        'CV' => 'Cabo Verde',
        'EG' => 'Egito',
        'ET' => 'Etiópia',
        'GH' => 'Gana',
        'KE' => 'Quénia',
        'MA' => 'Marrocos',
        'MZ' => 'Moçambique',
        'NG' => 'Nigéria',
        'SN' => 'Senegal',
        'ZA' => 'África do Sul',
        'TN' => 'Tunísia',

        // ===== ÁSIA =====
        'AF' => 'Afeganistão',
        'SA' => 'Arábia Saudita',
        'AM' => 'Arménia',
        'AZ' => 'Azerbaijão',
        'BD' => 'Bangladexe',
        'KH' => 'Camboja',
        'CN' => 'China',
        'KR' => 'Coreia do Sul',
        'KP' => 'Coreia do Norte',
        'AE' => 'Emirados Árabes Unidos',
        'PH' => 'Filipinas',
        'GE' => 'Geórgia',
        'IN' => 'Índia',
        'ID' => 'Indonésia',
        'IR' => 'Irão',
        'IQ' => 'Iraque',
        'IL' => 'Israel',
        'JP' => 'Japão',
        'KZ' => 'Cazaquistão',
        'LB' => 'Líbano',
        'MY' => 'Malásia',
        'MN' => 'Mongólia',
        'NP' => 'Nepal',
        'PK' => 'Paquistão',
        'QA' => 'Catar',
        'SG' => 'Singapura',
        'LK' => 'Sri Lanka',
        'TH' => 'Tailândia',
        'TR' => 'Turquia',
        'VN' => 'Vietname',

        // ===== OCEÂNIA =====
        'AU' => 'Austrália',
        'NZ' => 'Nova Zelândia',

    ];

});